"""add_summary_fields_to_chat_sessions

Revision ID: e79fd9002acd
Revises: 93ad64d6281f
Create Date: 2026-06-20 20:00:59.745624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e79fd9002acd'
down_revision: Union[str, None] = '93ad64d6281f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('chat_sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column(
        'chat_sessions',
        sa.Column('summarized_through', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summarized_through')
    op.drop_column('chat_sessions', 'summary')
    # ### end Alembic commands ###
